name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16

    - name: Build executable
      run: go build -o miniredis ./main/main.go

    - name: Test
      run: make

  build-alpine:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Test
      run: ls -al
    - name: Build
      run: docker run --rm --mount type=bind,source="$(pwd)",target=/opt/code golang:1.16-alpine sh -c 'cd /opt/code && go build -o miniredis ./main/main.go'
    - name: Test2
      run: ls -al

