name: Publish Artifacts

on:
  release:
    types: [published]

jobs:
  buildLinuxExecutable:
    name: Build Exceutable for Linux
    runs-on: ubuntu-latest
    steps:
    - name: Check out the repo
      uses: actions/checkout@v2
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16
    - name: Build
      run: go build -v ./...
    - name: Upload to release
      id: upload-release-asset 
      uses: actions/upload-release-asset@v1
      env:
       GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ./miniredis
        asset_name: miniredis.linux-amd64.bin
        asset_content_type: application/octet-stream

  buildMacOSExecutable:
    name: Build Native Image Exceutables for MacOS
    runs-on: macos-latest
    steps:
    - name: Check out the repo
      uses: actions/checkout@v2
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16
    - name: Build
      run: go build -v ./...
    - name: Upload to release
      id: upload-release-asset 
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ./miniredis
        asset_name: miniredis.macos-amd64.bin
        asset_content_type: application/octet-stream
